CUDA_VISIBLE_DEVICES=0 python src/train_bash.py \
    --use_v2 \
    --stage sft \
    --do_train \
    --dataset spider_cognition \
    --finetuning_type lora \
    --output_dir output/cognition \
    --overwrite_cache \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 2 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --warmup_steps 0 \
    --learning_rate 1e-3 \
    --num_train_epochs 10.0 \
    --fp16